overblog_graphql:
  definitions:
    schema:
      query: Query
      mutation: Mutation
      types: [Risific, Chapter, User]
    mappings:
      auto_discover: false
      types:
      - type: yaml
        dir: "%kernel.project_dir%/config/graphql/types"
        suffix: ~
