framework:
  messenger:
    transports:
      amqp: "%env(MESSENGER_TRANSPORT_DSN)%"
      risifics: "%env(MESSENGER_TRANSPORT_DSN)%/risifics"

    routing:
      'App\Message\AddRisificMessage': risifics
      '*': amqp
