ChapterOrderField:
  type: enum
  config:
    description: Properties by which chapters can be ordered
    values:
      CREATED_AT:
        value: createdAt
        description: Allows ordering a list of chapters by when they were created.
      POSITION:
        value: position
        description: Allows ordering a list of chapters by their position.