DeleteUserFavoritePayload:
  type: relay-mutation-payload
  config:
    fields:
      deletedRisificFavoriteId:
        type: ID!
        description: The ID of the Risific which has been unfavorited
