Query:
  type: object
  config:
    fields:
      node:
        builder: "Relay::Node"
        builderConfig:
          nodeInterfaceType: Node
          idFetcher: '@=resolver("App\\GraphQL\\Resolver\\GlobalIdResolver", [value])'
      risifics:
        description: Get all Risifics.
        type: RisificConnection!
        argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\RisificsResolver", [args])'
        args:
          first:
            type: Int
            defaultValue: 100
          orderBy:
            type: RisificOrder
            defaultValue: { field: CREATED_AT, direction: DESC }
      risific:
        type: Risific
        description: Search a particular Risific.
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\RisificResolver", [args])'
        args:
          search: RisificSearch!
      chapter:
        type: Chapter
        description: Get a given chapter by a position and a Risific slug
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\ChapterResolver", [args])'
        args:
          risificSlug: String!
          position: Int!