RisificSearchField:
  type: enum
  config:
    description: Properties by which risifics can be searched
    values:
      ID:
        value: id
        description: Allows searching risifics by their ID.
      SLUG:
        value: slug
        description: Allows searching risifics by their slug.