Risific:
  type: object
  inherits: [Node]
  config:
    interfaces: [Node]
    description: A risific made by a khey
    fields:
      id:
        description: The ID of the risific
      createdAt:
        description: The creation date of the risific
        type: DateTime!
      title:
        description: The title of the risific
        type: String!
      slug:
        description: The slug (seo-friendly name) of the risific
        type: String!
      viewerHasFavorited:
        access: "@=isAuthenticated()"
        description: Does the connected user has favorited this risific?
        type: Boolean!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Risific\\RisificViewerHasFavorited", [value, getUser()])'
      chapter:
        type: Chapter
        description: Get a particular chapter by its position
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Risific\\RisificChapterResolver", [value, args])'
        args:
          position:
            type: Int!
      chaptersCount:
        type: Int!
        description: The number of chapters associated to the risific
      chapters:
        type: ChapterConnection!
        description: The associated chapters of the risific
        argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Risific\\RisificChaptersResolver", [value, args])'
        args:
          first:
            type: Int
            defaultValue: 100
          orderBy:
            type: ChapterOrder
            defaultValue: { field: position, direction: DESC }