User:
  type: object
  inherits: [Node]
  config:
    interfaces: [Node]
    description: A user
    fields:
      id:
        description: The ID of the user
      roles:
        description: The role(s) of the user
        type: '[UserRole]'
        access: '@=serv("App\\GraphQL\\Resolver\\User\\UserIsGrantedResolver").isGranted(getUser(), value)'
      createdAt:
        description: The signup date of the user
        type: DateTime!
        access: '@=serv("App\\GraphQL\\Resolver\\User\\UserIsGrantedResolver", [getUser(), value])'
      username:
        description: The username of the user
        type: String!
      favorites:
        description: The favorited risifics of the user
        type: UserFavoriteConnection!
        argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\User\\UserFavoriteResolver", [value, args])'
        args:
          first:
            type: Int
            defaultValue: 100
          orderBy:
            type: UserFavoriteOrder
            defaultValue: { field: favoritedAt, direction: DESC }
      email:
        description: The email of the user
        type: String!
        access: '@=serv("App\\GraphQL\\Resolver\\User\\UserIsGrantedResolver").isGranted(getUser(), value)'